---
# tasks file for ansible-alacritty
- name: Make sure .config/alacritty exists
  file:
    path: "{{ansible_env.HOME}}/.config/alacritty"
    state: directory

- name: Template alacritty.yml
  template:
    src: alacritty.yml.j2
    dest: "{{ansible_env.HOME}}/.config/alacritty/alacritty.yml"
